### ISSUE TITLE
Integers are used instead of floating point values

### ISSUE THREAD

**Issue by thisisthekap** [ryancheung/SkiaTextRenderer#7]
* I would suggest to use SKRectangle instead of Rectangle
* Use `float maxLineWidth` for all `MeasureText` overloads

I would be happy to submit a PR containing these changes.

**Comment by ryancheung** [comment]
Good point. Any improvements on this lib is welcomed. Thanks!

**Comment by thisisthekap** [comment]
@ryancheung Just created PR #8
